esphome:
  name: pelletkachel
  friendly_name: Pellet Kachel

api:
  encryption:
    key: !secret encryption_key

esp8266:
  board: d1_mini
  
ota:
  - platform: esphome
    password: !secret ota_key

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pelletkachel Fallback Hotspot"
    password: !secret pelletkachel_api_password

packages:
  remote_package_files:
    url: https://github.com/AppelBoomHD/ESPHome-Duepi.git
    files: [
      components/script.yaml, 
      components/globals.yaml, 
      components/sensor.yaml, 
      components/switch.yaml, 
      components/climate.yaml, 
      components/uart.yaml, 
      components/time.yaml, 
      components/text_sensor.yaml
      ]
    ref: main #change if you like to test a beta version
    refresh: 0d 
