api:
  services:
    - service: write
      variables:
        command: string
      then:
        - wait_until:
            condition:
              lambda: 'return (id(uart_send) == 0);'
            timeout: 1s
        - lambda: id(uart_send) = 10;
        - script.execute:         
            id: UART_CMD
            command_in: !lambda return command;        
        - script.wait: UART_CMD
        - wait_until:
            condition:
              lambda: 'return (id(uart_send) == 0);'
            timeout: 100ms 
esphome:
  on_boot:
    - priority: -10
      then: 
        - lambda: |- 
            id(uart_send) = 0;
            id(room_temp_stove).publish_state(17.0);
            id(power_level).publish_state(1);
            id(pellet_speed).publish_state(1);
            id(fan_mode) = 1;
            id(flu_gas_temp).publish_state(17.0);
            id(exh_fan_speed).publish_state(0);
            id(burner_status).publish_state("All OK, startup");
            id(Stove).target_temperature = 21.0;
